# Generated by Django 3.2.6 on 2021-08-04 09:25

from django.db import migrations


def create_site_settings(apps, schema_editor):
    Settings = apps.get_model('settings', 'Settings')
    Settings.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site_settings)
    ]
