# Generated by Django 3.2.6 on 2021-08-11 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_auto_20210804_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notify_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
