# Generated by Django 3.2.6 on 2021-08-12 13:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0003_settings_notify_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=0, default='30', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Delivery cost'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='notify_users',
            field=models.ManyToManyField(help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settings',
            name='order_prepayment_start_from',
            field=models.DecimalField(decimal_places=0, default='400', help_text='Amount, from which prepayment will be required', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Order prepayment start from'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='prepayment_percent',
            field=models.DecimalField(decimal_places=0, default='25', help_text='From total order amount', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Prepayment percent'),
        ),
    ]
