# Generated by Django 3.2.6 on 2021-08-12 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_auto_20210812_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='notify_users',
            field=models.ManyToManyField(help_text='Hold down "Control", or "Command" on a Mac, to select more than one.\nUsers that will receive new order notifications.\nNote: users must have email filled in their profile', to=settings.AUTH_USER_MODEL, verbose_name='Notify users'),
        ),
    ]
