# Generated by Django 3.2.6 on 2021-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(help_text='Shows in miniatures', max_length=100, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='title',
            field=models.CharField(help_text='Shows in sections on the page', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='possible_additions',
            field=models.ManyToManyField(blank=True, related_name='purpose_menu_items', to='menu.Addition', verbose_name='Possible additions'),
        ),
    ]
