# Generated by Django 3.2.6 on 2021-08-12 10:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210809_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
