# Generated by Django 3.2.6 on 2021-08-12 10:45

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='menu_images'),
        ),
    ]
