# Generated by Django 3.2.6 on 2021-08-12 10:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='action_images'),
        ),
    ]
