# Generated by Django 3.2.6 on 2021-08-12 10:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_action_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(upload_to='menu_category_icons'),
        ),
    ]
