# Generated by Django 3.2.6 on 2021-08-12 13:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menucategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='action_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(upload_to='menu_category_icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='menu_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='possible_additions',
            field=models.ManyToManyField(blank=True, help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='purpose_menu_items', to='menu.Addition', verbose_name='Possible additions'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Price'),
        ),
    ]
