# Generated by Django 3.2.6 on 2021-10-22 09:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20210812_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='hq_image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='hq_menu_images', verbose_name='Image'),
        ),
    ]
