# Generated by Django 3.2.6 on 2021-08-07 08:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import order.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session key')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Total amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Human name')),
                ('phone_number', models.CharField(help_text='Format: "+380123456789"', max_length=13, unique=True, validators=[order.validators.phone_number_validator], verbose_name='Phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session key')),
                ('delivery_method', models.CharField(choices=[('COURIER', 'Courier'), ('SELF_PICKUP', 'Self-pickup')], max_length=50, verbose_name='Delivery method')),
                ('self_pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Self-pickup time')),
                ('peoples_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Peoples count')),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Customer comment')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Total amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('LIQPAY', 'LiqPay')], max_length=50, verbose_name='Payment method')),
                ('prepayment_required', models.BooleanField(verbose_name='Prepayment required')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PREPAYMENT', 'Prepayment'), ('FULL_PAYMENT', 'Full payment')], max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not paid')], default='NOT_PAID', max_length=50, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Amount')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order transaction',
                'verbose_name_plural': 'Order transactions',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Count')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem', verbose_name='Menu item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement', models.CharField(max_length=100, verbose_name='Settlement')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('building_number', models.CharField(max_length=15, verbose_name='Building number')),
                ('apartment_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Apartment number')),
                ('entrance_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Entrance number')),
                ('floor_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Floor number')),
                ('door_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Door phone number')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Delivery address',
                'verbose_name_plural': 'Delivery addresses',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Count')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Total amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('additions', models.ManyToManyField(to='menu.Addition', verbose_name='Additions')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.cart', verbose_name='Cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu.menuitem', verbose_name='Menu item')),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
            },
        ),
        migrations.CreateModel(
            name='AdditionHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('addition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_items', to='menu.addition', verbose_name='Addition')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='order.orderitem', verbose_name='Order item')),
            ],
            options={
                'verbose_name': 'Addition history item',
                'verbose_name_plural': 'Addition history items',
            },
        ),
    ]
