# Generated by Django 3.2.6 on 2021-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210809_1816'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionHistoryItem',
            new_name='AdditionItem',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='additions',
            field=models.ManyToManyField(related_name='cart_items', to='menu.Addition', verbose_name='Additions'),
        ),
    ]
