# Generated by Django 3.2.6 on 2021-08-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210809_1816'),
        ('order', '0002_auto_20210809_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionitem',
            name='addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addition_items', to='menu.addition', verbose_name='Addition'),
        ),
    ]
