# Generated by Django 3.2.6 on 2021-08-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210809_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
