# Generated by Django 3.2.6 on 2021-08-12 13:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20210812_1619'),
        ('order', '0006_ordertransaction_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='additions',
            field=models.ManyToManyField(help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='cart_items', to='menu.Addition', verbose_name='Additions'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=0, max_digits=6)], verbose_name='Amount'),
        ),
    ]
