# Generated by Django 3.2.6 on 2021-10-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210812_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional data'),
        ),
    ]
